version: '3'

# Elastic images: https://www.docker.elastic.co/
# Configuring elastic: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-prod-cluster-composefile

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    # configuring: https://www.elastic.co/guide/en/logstash/current/configuration.html
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana

  mysql:
    image: percona/percona-server:5.7
    container_name: mysql

volumes:
  esdata:
    driver: local